import type { SectionAData } from './types';

export const sectionAData: SectionAData[] = [
  {
    id: "251201",
    title: "2025年12月 第一套",
    topic: "中年开始锻炼是否为时已晚",
    article: "By now, it is generally accepted that regular exercise comes with an assortment of health benefits for people who maintain the habit over time. But is it __(26)__ too late to start?\nNew research looked at people who increased their exercise levels after their 40s beyond levels they had when they were younger and those individuals showed declines in their risk of early __(27)__ which were similar to those of people who exercised consistently throughout their lives. This was a __(28)__ of 32% to 35% compared to people who did not exercise. Those who began exercising in middle age also saw reductions in their incidence of __(29)__ diseases, such as heart disease and cancer, which were similar to the steady exercisers.\nSo why bother exercising consistently throughout your life? The authors of the study __(30)__ that some might interpret the study's findings to mean that they can delay starting an exercise program but this would be a mistake. There are other benefits, both mental and physical, to staying consistently active that we should not __(31)__. These real health benefits include better __(32)__ functioning and lowered risk of gaining weight. The latter is __(33)__ important given the global obesity epidemic. In addition, experts assert that starting younger is better because, if you make a habit of exercising when you are young, you are more likely to keep up those __(34)__ later in life. It is ideal, then, for people to start exercising when they are children or __(35)__, and it is good to maintain an active lifestyle at all times regardless of your age. However, this study does indicate that, if you have not been active, you can still benefit if you start becoming active in your 40s and 50s.",
    blanks: [
      { number: 26, position: "is it __(26)__ too late", answer: "H", answerWord: "ever", partOfSpeech: "adverb", analysis: { why_correct: "\"Is it ever too late to start?\" 是一个常见的英文修辞疑问句式，意思是\"真的会太晚吗？\"。ever 在此处用于疑问句中加强语气，表示\"到底、究竟\"，整句暗示\"其实永远不会太晚\"。", grammar_clue: "空格位于 is it 和 too late 之间，需要一个副词来修饰 too late。", context_clue: "文章开头铺垫了锻炼的好处，然后用 But 转折提出疑问，ever 配合疑问句式表达\"是否真的太晚\"这一核心问题。", collocation: "Is it ever too late to...? 是固定的英文表达。", common_mistakes: [{ wrong: "B (arbitrarily)", reason: "arbitrarily 意为\"任意地、武断地\"，放入此处语义不通。而且 arbitrarily too late 不构成合理搭配。" }] } },
      { number: 27, position: "risk of early __(27)__", answer: "J", answerWord: "mortality", partOfSpeech: "noun", analysis: { why_correct: "\"risk of early mortality\" 表示\"早亡风险\"，是医学和健康研究中的标准表达。文章讨论的是锻炼对降低死亡风险的影响。", grammar_clue: "空格前面是 early（形容词），后面需要一个名词。of 后面也需要名词。", context_clue: "研究发现中年开始锻炼的人，其早亡风险下降了——这和终身坚持锻炼的人相似。这是关于生死层面的结论。", collocation: "early mortality / risk of mortality 都是学术写作中的高频搭配。", common_mistakes: [{ wrong: "G (drop)", reason: "drop 是动词/名词，但 risk of early drop 语义不明确，不是健康领域的自然搭配。" }] } },
      { number: 28, position: "This was a __(28)__ of 32% to 35%", answer: "G", answerWord: "drop", partOfSpeech: "noun", analysis: { why_correct: "\"a drop of 32% to 35%\" 意为\"下降了32%到35%\"。文章正在描述研究数据——与不锻炼者相比，锻炼者的风险下降幅度。", grammar_clue: "a __(28)__ of 数字%，冠词 a 后面需要一个可数名词，能够和 of + 百分比 搭配。", context_clue: "前文说 showed declines in their risk，此处用 drop 继续量化这个\"下降\"。", collocation: "a drop of X% 是描述数据下降的标准表达。类似的还有 a decline of / a decrease of。", common_mistakes: [{ wrong: "N (stereotype)", reason: "stereotype 意为\"刻板印象\"，与数据下降完全无关。" }] } },
      { number: 29, position: "incidence of __(29)__ diseases, such as heart disease and cancer", answer: "C", answerWord: "chronic", partOfSpeech: "adjective", analysis: { why_correct: "\"chronic diseases\" 意为\"慢性疾病\"。后面紧跟 such as heart disease and cancer 举例说明，心脏病和癌症正是典型的慢性病。", grammar_clue: "空格在 of 和 diseases 之间，需要形容词修饰 diseases。", context_clue: "文章讨论的是长期锻炼对疾病发病率的影响，提到的心脏病和癌症都是慢性病的代表。", collocation: "chronic diseases / chronic illness 是医学领域最常见的搭配之一。", common_mistakes: [{ wrong: "D (cognitive)", reason: "cognitive diseases（认知类疾病）虽然语法可行，但后面举例是心脏病和癌症，不属于认知类疾病。" }] } },
      { number: 30, position: "The authors of the study __(30)__ that some might interpret...", answer: "E", answerWord: "concede", partOfSpeech: "verb", analysis: { why_correct: "\"concede that...\" 意为\"承认、让步说……\"。作者承认有人可能会曲解研究结果，但紧接着说 this would be a mistake，这是一种\"先退后进\"的论证策略。", grammar_clue: "主语 The authors 后面需要一个及物动词，后接 that 从句。", context_clue: "文章进入了论证部分：为什么不能因为中年锻炼也有效就拖延？作者先\"承认\"可能的误读，再反驳。", collocation: "concede that... 是学术写作中常见的让步表达。", common_mistakes: [{ wrong: "M (refute)", reason: "refute 意为\"反驳\"，但作者此处不是在反驳某个观点，而是在\"承认\"人们可能产生的误解——refute 的语义方向相反。" }] } },
      { number: 31, position: "benefits...that we should not __(31)__", answer: "F", answerWord: "disregard", partOfSpeech: "verb", analysis: { why_correct: "\"should not disregard\" 意为\"不应忽视\"。文章在强调：即使中年开始锻炼有效，终身锻炼还有其他精神和身体上的好处，这些不该被忽略。", grammar_clue: "should not 后面需要动词原形。that 引导定语从句修饰 benefits。", context_clue: "上文说 there are other benefits，接着说这些好处 we should not __31__，逻辑上显然是\"不应忽视\"。", collocation: "disregard benefits / disregard the importance of 是常见搭配。", common_mistakes: [{ wrong: "I (maneuver)", reason: "maneuver 意为\"操纵、策略性行动\"，和\"不应忽视好处\"这个语境完全不搭。" }] } },
      { number: 32, position: "better __(32)__ functioning", answer: "D", answerWord: "cognitive", partOfSpeech: "adjective", analysis: { why_correct: "\"cognitive functioning\" 意为\"认知功能\"。锻炼对大脑认知能力的提升是已被广泛研究证实的。", grammar_clue: "空格在 better 和 functioning 之间，需要形容词。better 修饰整体 cognitive functioning。", context_clue: "上文说有 mental and physical 两方面的好处，cognitive functioning 属于 mental benefits 的范畴。", collocation: "cognitive functioning / cognitive ability / cognitive skills 都是极高频搭配。", common_mistakes: [{ wrong: "C (chronic)", reason: "chronic functioning 不是自然搭配。chronic 通常修饰负面事物（疾病、疼痛），不修饰 functioning。" }] } },
      { number: 33, position: "The latter is __(33)__ important given the global obesity epidemic", answer: "K", answerWord: "particularly", partOfSpeech: "adverb", analysis: { why_correct: "\"particularly important\" 意为\"尤其重要\"。考虑到全球肥胖流行，降低体重增长风险这一好处显得尤其重要。", grammar_clue: "空格在 is 和 important 之间，需要副词修饰形容词 important。", context_clue: "given the global obesity epidemic 提供了强调的理由，particularly 起到语义加强的作用。", collocation: "particularly important / particularly relevant / particularly significant 都是学术写作常见搭配。", common_mistakes: [{ wrong: "B (arbitrarily)", reason: "arbitrarily important 意为\"随意地重要\"，语义荒谬，不构成合理搭配。" }] } },
      { number: 34, position: "more likely to keep up those __(34)__ later in life", answer: "L", answerWord: "patterns", partOfSpeech: "noun", analysis: { why_correct: "\"keep up those patterns\" 意为\"保持那些习惯/模式\"。年轻时养成的锻炼习惯，更可能在以后的生活中延续。", grammar_clue: "those 后面需要复数名词。keep up 是动词短语，意为\"保持、维持\"。", context_clue: "前文说 if you make a habit of exercising when you are young，所以 patterns 指的就是锻炼的行为模式/习惯。", collocation: "keep up patterns / behavior patterns / exercise patterns 是自然搭配。", common_mistakes: [{ wrong: "A (adolescents)", reason: "adolescents 是名词\"青少年\"，但 keep up those adolescents 语义不通——你不能\"保持那些青少年\"。" }] } },
      { number: 35, position: "when they are children or __(35)__", answer: "A", answerWord: "adolescents", partOfSpeech: "noun", analysis: { why_correct: "\"children or adolescents\" 意为\"儿童或青少年\"。文章建议人们从年幼时就开始锻炼，children 和 adolescents 构成并列，覆盖整个未成年阶段。", grammar_clue: "or 连接两个并列成分，前面是 children（名词复数），后面也需要名词复数。", context_clue: "整段论述\"越早开始越好\"的观点，children or adolescents 涵盖了年轻群体。", collocation: "children and/or adolescents 在教育和健康研究中是标准表达。", common_mistakes: [{ wrong: "L (patterns)", reason: "children or patterns 语义荒谬——\"当他们是孩子或模式时\"不成立。" }] } },
    ],
    options: [
      { letter: "A", word: "adolescents", pos: "n. 青少年", used: true },
      { letter: "B", word: "arbitrarily", pos: "adv. 任意地；武断地", used: false },
      { letter: "C", word: "chronic", pos: "adj. 慢性的；长期的", used: true },
      { letter: "D", word: "cognitive", pos: "adj. 认知的", used: true },
      { letter: "E", word: "concede", pos: "v. 承认；让步", used: true },
      { letter: "F", word: "disregard", pos: "v. 忽视；不理会", used: true },
      { letter: "G", word: "drop", pos: "n./v. 下降；下落", used: true },
      { letter: "H", word: "ever", pos: "adv. 曾经；到底", used: true },
      { letter: "I", word: "maneuver", pos: "n./v. 操纵；策略", used: false },
      { letter: "J", word: "mortality", pos: "n. 死亡率；死亡", used: true },
      { letter: "K", word: "particularly", pos: "adv. 尤其；特别", used: true },
      { letter: "L", word: "patterns", pos: "n. 模式；习惯", used: true },
      { letter: "M", word: "refute", pos: "v. 反驳；驳斥", used: false },
      { letter: "N", word: "stereotype", pos: "n. 刻板印象", used: false },
      { letter: "O", word: "vocal", pos: "adj. 直言不讳的；声音的", used: false },
    ],
    distractors: [
      { letter: "B", word: "arbitrarily", explanation: "意为\"任意地、武断地\"。文中没有任何位置需要表达\"随意\"或\"武断\"的含义。它作为副词，在本文所有需要副词的空格中都不构成合理搭配。" },
      { letter: "I", word: "maneuver", explanation: "意为\"操纵、调动、策略性行动\"。这个词偏军事/策略语境，和本文讨论的健康与锻炼话题没有交集。" },
      { letter: "M", word: "refute", explanation: "意为\"反驳、驳斥\"。第30空可能会让人犹豫，但作者不是在\"反驳\"某观点，而是\"承认\"人们可能的误读后再纠正——这是 concede 的用法，不是 refute。" },
      { letter: "N", word: "stereotype", explanation: "意为\"刻板印象\"。文中没有涉及偏见或社会认知方面的讨论，和运动健康话题不相关。" },
      { letter: "O", word: "vocal", explanation: "意为\"直言不讳的\"或\"与声音有关的\"。文中没有讨论发言、表态或声音的话题，无法融入任何空格。" },
    ],
    vocabulary_collection: [
      { expression: "an assortment of", meaning: "各种各样的", example: "an assortment of health benefits" },
      { expression: "early mortality", meaning: "早亡", example: "declines in their risk of early mortality" },
      { expression: "a drop of X%", meaning: "下降了X%", example: "a drop of 32% to 35%" },
      { expression: "chronic diseases", meaning: "慢性疾病", example: "incidence of chronic diseases" },
      { expression: "concede that", meaning: "承认……", example: "The authors concede that some might interpret..." },
      { expression: "cognitive functioning", meaning: "认知功能", example: "better cognitive functioning" },
      { expression: "particularly important", meaning: "尤其重要", example: "particularly important given the global obesity epidemic" },
      { expression: "keep up patterns", meaning: "保持习惯/模式", example: "keep up those patterns later in life" },
      { expression: "children or adolescents", meaning: "儿童或青少年", example: "start exercising when they are children or adolescents" },
      { expression: "disregard", meaning: "忽视", example: "benefits that we should not disregard" },
    ],
  },
  {
    id: "251202",
    title: "2025年12月 第二套",
    topic: "AI时代人类智能和创造力的价值",
    article: "We humans love to believe we are special, but science and technology have repeatedly proved this conviction wrong. People __(26)__ thought that humans were the only animals to use tools, to form teams or to propagate culture, but science has shown that other animals do each of these things.\nMeanwhile, technology has quashed, one by one, claims that __(27)__ tasks require a human brain. The first adding machine was invented in 1623. This past year, a computer-generated work won an art contest. I believe the moment when computers meet and __(28)__ human intelligence is on the horizon.\nHow will human intelligence and creativity be valued when machines become smarter and more creative than the brightest people? There will likely be a spectrum. In some __(29)__, people still value humans doing things, even if a computer can do it better. It's been a quarter of a century since a computer beat world champion Garry Kasparov, but human chess hasn't gone away.\nIn other fields, human skill will seem costly and __(30)__. Take illustration for example: most readers don't care whether the graphic __(31)__ a magazine article was drawn by a person or a computer -- they just want it to be relevant, new and perhaps __(32)__.\nAnd, of course, this question isn't black or white. Many fields will be a __(33)__, where some humans find a lucky place, but most of the work is done by computers, like in manufacturing today, where much of the work is accomplished by robots, but some humans must be there to __(34)__ the machines.\nIf history is any guide, it's almost certain that advances in AI will cause more jobs to __(35)__, that creative workers with human-only skills will become richer but fewer in number, and that those who own creative technology will become the new ultra-rich.",
    blanks: [
      { number: 26, position: "People __(26)__ thought that humans", answer: "I", answerWord: "once", partOfSpeech: "adverb", analysis: { why_correct: "\"People once thought\" 意为\"人们曾经认为\"。整句话在描述一个已经被推翻的旧观念——人类是唯一会使用工具的动物——once 表示这是过去的看法。", grammar_clue: "空格位于主语 People 和谓语 thought 之间，需要副词。", context_clue: "后面紧跟 but science has shown...，形成\"曾经以为……但科学证明不是\"的转折结构，once 完美呼应这个时间对比。", collocation: "once thought / once believed 是叙述旧观点的经典搭配。", common_mistakes: [{ wrong: "N (tentatively)", reason: "tentatively 意为\"试探性地\"，People tentatively thought 暗示人们犹豫地思考，但原文表达的是一种曾经坚定持有、后来被推翻的信念。" }] } },
      { number: 27, position: "claims that __(27)__ tasks require a human brain", answer: "B", answerWord: "cognitive", partOfSpeech: "adjective", analysis: { why_correct: "\"cognitive tasks\" 意为\"认知任务\"。技术一步步推翻了\"认知任务必须由人脑完成\"的说法——从计算器到AI生成艺术作品。", grammar_clue: "空格在 that 从句中，位于 tasks 前面，需要形容词修饰名词。", context_clue: "前文说 technology has quashed claims，后面举例从计算到艺术创作，这些都属于认知层面的任务。", collocation: "cognitive tasks / cognitive abilities / cognitive processes 是心理学和AI领域的核心术语。", common_mistakes: [{ wrong: "H (intuitive)", reason: "intuitive tasks 虽然语法可行，但文章强调的不是\"直觉性任务\"，而是广义的\"需要大脑的任务\"。" }] } },
      { number: 28, position: "computers meet and __(28)__ human intelligence", answer: "M", answerWord: "surpass", partOfSpeech: "verb", analysis: { why_correct: "\"meet and surpass\" 意为\"达到并超越\"。作者认为计算机追上并超过人类智能的那一刻即将到来。", grammar_clue: "and 连接两个并列动词，前面是 meet，后面需要同形式的动词原形。", context_clue: "整段在讨论AI的进步趋势，is on the horizon 表示\"即将到来\"，surpass 表达了从\"追平\"到\"超越\"的递进。", collocation: "meet and surpass / meet and exceed 是描述赶超的固定表达。", common_mistakes: [{ wrong: "E (evoking)", reason: "evoking 意为\"唤起、引发\"，meet and evoking 形式不对（应为 evoke），且语义不通。" }] } },
      { number: 29, position: "In some __(29)__, people still value humans", answer: "C", answerWord: "domains", partOfSpeech: "noun", analysis: { why_correct: "\"In some domains\" 意为\"在某些领域\"。文章接下来举了国际象棋的例子——在某些领域，人们仍然看重人类的表现。", grammar_clue: "In some + 复数名词，表示\"在某些……中\"。", context_clue: "后文紧跟 In other fields，形成\"某些领域……另一些领域\"的对比结构。domains 和 fields 是同义替换。", collocation: "in some domains / across various domains 是学术表达。", common_mistakes: [{ wrong: "L (stances)", reason: "stances 意为\"立场、态度\"，In some stances 不是自然英语表达。" }] } },
      { number: 30, position: "human skill will seem costly and __(30)__", answer: "K", answerWord: "redundant", partOfSpeech: "adjective", analysis: { why_correct: "\"costly and redundant\" 意为\"昂贵且多余\"。在某些领域（如插图），如果电脑能做得更好更便宜，人类技能就显得又贵又没必要。", grammar_clue: "and 连接两个并列形容词，前面是 costly，后面需要形容词。", context_clue: "后文举例说读者不在乎图是人画的还是电脑画的，说明人工技能在这些领域变得\"多余\"。", collocation: "costly and redundant 是描述被淘汰技能的自然搭配。", common_mistakes: [{ wrong: "D (entertaining)", reason: "costly and entertaining 语义矛盾且不符合语境。" }] } },
      { number: 31, position: "the graphic __(31)__ a magazine article", answer: "A", answerWord: "accompanying", partOfSpeech: "verb (present participle / adjective)", analysis: { why_correct: "\"the graphic accompanying a magazine article\" 意为\"配合杂志文章的图片\"。accompanying 在此做后置定语或现在分词，修饰 graphic。", grammar_clue: "the graphic __(31)__ a magazine article 结构中，空格需要一个能连接 graphic 和 a magazine article 的词。", context_clue: "这里讨论的是杂志文章的配图——读者不在乎它是谁画的。", collocation: "graphic/image/illustration accompanying an article 是出版行业标准表达。", common_mistakes: [{ wrong: "E (evoking)", reason: "the graphic evoking a magazine article 语义不顺——图片是\"配合\"文章的，不是\"唤起\"文章的。" }] } },
      { number: 32, position: "relevant, new and perhaps __(32)__", answer: "D", answerWord: "entertaining", partOfSpeech: "adjective", analysis: { why_correct: "\"relevant, new and perhaps entertaining\" 意为\"相关的、新颖的、或许还有趣的\"。读者对配图的要求就是这些。", grammar_clue: "三个并列形容词用 and 连接，前面有 relevant 和 new，最后一个也需要形容词。", context_clue: "perhaps 表示\"也许\"，暗示第三个要求不是必须的但值得期待——\"有趣\"正好符合这个\"锦上添花\"的语气。", collocation: "relevant, new and entertaining 是描述内容品质的自然组合。", common_mistakes: [{ wrong: "H (intuitive)", reason: "relevant, new and perhaps intuitive 语义上不太通顺——读者期待配图\"直觉的\"不如期待它\"有趣\"来得自然。" }] } },
      { number: 33, position: "Many fields will be a __(33)__", answer: "F", answerWord: "hybrid", partOfSpeech: "noun", analysis: { why_correct: "\"a hybrid\" 意为\"混合体\"。许多领域将是人机混合的状态——部分工作由人做，大部分由机器完成。", grammar_clue: "a + 单数名词。后面 where 引导定语从句解释这个\"混合体\"的特征。", context_clue: "后文说 some humans find a lucky place, but most of the work is done by computers，这正是\"混合\"的定义。", collocation: "a hybrid of... / hybrid model / hybrid approach 是描述人机协作的常用表达。", common_mistakes: [{ wrong: "G (impetus)", reason: "impetus 意为\"推动力\"。Many fields will be an impetus 语义不通。" }] } },
      { number: 34, position: "some humans must be there to __(34)__ the machines", answer: "J", answerWord: "oversee", partOfSpeech: "verb", analysis: { why_correct: "\"oversee the machines\" 意为\"监督/管理机器\"。即使大部分工作由机器人完成，仍需要人类在场监督。", grammar_clue: "to + 动词原形，构成不定式表目的。宾语是 the machines。", context_clue: "前文说 much of the work is accomplished by robots, but some humans must be there to...，逻辑上人类留下来的目的是监管。", collocation: "oversee machines / oversee operations / oversee the process 是管理语境下的标准表达。", common_mistakes: [{ wrong: "M (surpass)", reason: "surpass the machines 意为\"超越机器\"，但文章说的是人类在工厂中的角色是\"监督\"而非\"超越\"。" }] } },
      { number: 35, position: "advances in AI will cause more jobs to __(35)__", answer: "O", answerWord: "vanish", partOfSpeech: "verb", analysis: { why_correct: "\"cause more jobs to vanish\" 意为\"导致更多工作岗位消失\"。AI进步的结果之一是就业岗位减少。", grammar_clue: "cause + 宾语 + to + 动词原形，这是 cause 的固定用法。", context_clue: "后文说 creative workers will become fewer in number，整段在预测AI时代的影响——工作消失是其中最直接的后果。", collocation: "jobs vanish / jobs disappear / jobs are eliminated 是讨论自动化影响时的常见表达。", common_mistakes: [{ wrong: "E (evoking)", reason: "cause more jobs to evoking 首先语法错误，其次语义不通。" }] } },
    ],
    options: [
      { letter: "A", word: "accompanying", pos: "v./adj. 伴随的；配合的", used: true },
      { letter: "B", word: "cognitive", pos: "adj. 认知的", used: true },
      { letter: "C", word: "domains", pos: "n. 领域", used: true },
      { letter: "D", word: "entertaining", pos: "adj. 有趣的；令人愉快的", used: true },
      { letter: "E", word: "evoking", pos: "v. 唤起；引发", used: false },
      { letter: "F", word: "hybrid", pos: "n./adj. 混合体；混合的", used: true },
      { letter: "G", word: "impetus", pos: "n. 推动力；动力", used: false },
      { letter: "H", word: "intuitive", pos: "adj. 直觉的；易懂的", used: false },
      { letter: "I", word: "once", pos: "adv. 曾经；一度", used: true },
      { letter: "J", word: "oversee", pos: "v. 监督；管理", used: true },
      { letter: "K", word: "redundant", pos: "adj. 多余的；被裁的", used: true },
      { letter: "L", word: "stances", pos: "n. 立场；态度", used: false },
      { letter: "M", word: "surpass", pos: "v. 超越；胜过", used: true },
      { letter: "N", word: "tentatively", pos: "adv. 试探性地", used: false },
      { letter: "O", word: "vanish", pos: "v. 消失；消逝", used: true },
    ],
    distractors: [
      { letter: "E", word: "evoking", explanation: "意为\"唤起、引发\"。文中没有任何空格需要表达\"唤起\"这个含义。" },
      { letter: "G", word: "impetus", explanation: "意为\"推动力、动力\"。文中没有讨论什么东西充当推动力的语境。" },
      { letter: "H", word: "intuitive", explanation: "意为\"直觉的、易懂的\"。第32空可能有人考虑，但配图被期待是\"有趣的\"而非\"直觉的\"。" },
      { letter: "L", word: "stances", explanation: "意为\"立场、态度\"。In some stances 不是自然英语表达。" },
      { letter: "N", word: "tentatively", explanation: "意为\"试探性地\"。原文表达的不是\"试探性地认为\"，而是\"曾经坚定地认为\"后来被推翻。" },
    ],
    vocabulary_collection: [
      { expression: "propagate culture", meaning: "传播文化", example: "the only animals to propagate culture" },
      { expression: "quash claims", meaning: "推翻/否定说法", example: "technology has quashed claims" },
      { expression: "on the horizon", meaning: "即将到来", example: "the moment is on the horizon" },
      { expression: "cognitive tasks", meaning: "认知任务", example: "cognitive tasks require a human brain" },
      { expression: "meet and surpass", meaning: "达到并超越", example: "meet and surpass human intelligence" },
      { expression: "costly and redundant", meaning: "昂贵且多余", example: "human skill will seem costly and redundant" },
      { expression: "accompanying", meaning: "伴随的；配合的", example: "the graphic accompanying a magazine article" },
      { expression: "a hybrid", meaning: "混合体", example: "Many fields will be a hybrid" },
      { expression: "oversee the machines", meaning: "监督机器", example: "some humans must be there to oversee the machines" },
      { expression: "cause jobs to vanish", meaning: "导致工作消失", example: "advances in AI will cause more jobs to vanish" },
    ],
  },
  {
    id: "251203",
    title: "2025年12月 第三套",
    topic: "口音、方言与\"标准英语\"的迷思",
    article: "It's best to think of an accent as a distinct, systematic and rule-governed way of speaking. Accent is not a __(26)__ for dialect, but it's related. Dialect is an umbrella term for the way a community pronounces words, creates words, and orders words; accent refers to that first part only.\nMany __(27)__ presume that there is a single standard way of speaking in each country, with one single standard accent, and that this perceived standard is __(28)__ the best form of speech, but linguists often point out that the concept of a standard accent is better understood as an ideal rather than a __(29)__. In other words, no one speaks \"standard English\"; rather, it is an imagined way of using language that exists only in grammar and style books.\nOne reason linguists agree there is no one true standard is that, through the years, there have been __(30)__ supposed standards, depending on time and place. The standard for English in British newsreels from the 1950s, for example, differs greatly from the standard found on American national news broadcasts today. In fact, there has never been a single standard that's been fully agreed upon -- and broadcast outlets across the __(31)__ have never consistently held to those standards anyway.\nEven so, this idea of a standard accent is __(32)__ and many workplace and educational environments perpetuate the idea that accents that __(33)__ from the current standard are less appropriate, or even inappropriate. Scholars have found that southern U.S. accent features are more accepted in __(34)__ such as government, law and service-oriented workplaces, but less accepted in the technology sector. The acceptability of nonstandard accents may __(35)__ with differences in class and culture, with newer or higher prestige industries expecting more standard speech in the workplace.",
    blanks: [
      { number: 26, position: "Accent is not a __(26)__ for dialect", answer: "N", answerWord: "synonym", partOfSpeech: "noun", analysis: { why_correct: "\"not a synonym for dialect\" 意为\"不是方言的同义词\"。文章开头在区分 accent（口音）和 dialect（方言），强调它们相关但不等同。", grammar_clue: "a + 单数名词 + for，需要一个能和 for 搭配的名词。", context_clue: "后面紧跟 but it's related，说明二者有关联但不是同一回事。synonym 表示\"同义词\"，完美表达\"不等同\"的意思。", collocation: "a synonym for 是标准搭配，意为\"……的同义词/等同物\"。", common_mistakes: [{ wrong: "A (affix)", reason: "affix 意为\"词缀\"。a affix for dialect 既不合语法也不合语义。" }] } },
      { number: 27, position: "Many __(27)__ presume that there is a single standard", answer: "G", answerWord: "laymen", partOfSpeech: "noun", analysis: { why_correct: "\"Many laymen presume\" 意为\"许多外行人以为\"。文章对比外行人和语言学家的观点。", grammar_clue: "Many + 复数名词 + 动词。需要能做主语的复数名词。", context_clue: "后面用 but linguists often point out 形成对比，说明前面的观点来自非专业人士。", collocation: "laymen / laypersons 指\"外行、非专业人士\"，和 linguists 形成自然对比。", common_mistakes: [{ wrong: "I (properties)", reason: "Many properties presume 语义不通——\"许多属性以为\"不合逻辑。" }] } },
      { number: 28, position: "this perceived standard is __(28)__ the best form of speech", answer: "F", answerWord: "inherently", partOfSpeech: "adverb", analysis: { why_correct: "\"inherently the best\" 意为\"本质上是最好的\"。外行人认为标准口音\"天生就是\"最好的说话方式。", grammar_clue: "is __(28)__ the best，空格在系动词 is 和形容词最高级 the best 之间，需要副词。", context_clue: "这是外行人的观点，后面被语言学家反驳。inherently 暗示外行人把\"标准\"视为天然优越的。", collocation: "inherently better / inherently superior / inherently the best 是表达\"本质上更好\"的常见搭配。", common_mistakes: [{ wrong: "K (reciprocally)", reason: "reciprocally 意为\"互相地、相互地\"，is reciprocally the best 语义不通。" }] } },
      { number: 29, position: "an ideal rather than a __(29)__", answer: "J", answerWord: "reality", partOfSpeech: "noun", analysis: { why_correct: "\"an ideal rather than a reality\" 意为\"一种理想而非现实\"。语言学家认为\"标准口音\"只存在于想象中。", grammar_clue: "rather than a + 单数名词，和前面的 an ideal 形成对比。", context_clue: "后面紧跟解释：no one speaks 'standard English'，它是 an imagined way——都在强调它不是真实的。", collocation: "ideal vs. reality / an ideal rather than a reality 是经典的对比表达。", common_mistakes: [{ wrong: "L (specimen)", reason: "an ideal rather than a specimen 不构成有意义的对比。" }] } },
      { number: 30, position: "there have been __(30)__ supposed standards", answer: "H", answerWord: "multiple", partOfSpeech: "adjective", analysis: { why_correct: "\"multiple supposed standards\" 意为\"多个所谓的标准\"。不同时间和地点有不同的\"标准\"。", grammar_clue: "have been + 形容词 + 名词复数。", context_clue: "后面用 depending on time and place 解释为什么会有多个标准。", collocation: "multiple standards / multiple versions / multiple interpretations 都是常见搭配。", common_mistakes: [{ wrong: "O (unanimous)", reason: "unanimous supposed standards 意为\"一致同意的所谓标准\"，语义矛盾。" }] } },
      { number: 31, position: "broadcast outlets across the __(31)__", answer: "M", answerWord: "spectrum", partOfSpeech: "noun", analysis: { why_correct: "\"across the spectrum\" 意为\"在整个范围/各种类型中\"。各种各样的广播机构都没有一致地遵守那些所谓的标准。", grammar_clue: "across the + 单数名词。需要一个能表示\"范围、谱系\"的名词。", context_clue: "文章在强调不存在统一标准，连广播机构自己都没有一致地执行。", collocation: "across the spectrum / across the political spectrum / a broad spectrum 是高频表达。", common_mistakes: [{ wrong: "D (domains)", reason: "across the domains 不如 across the spectrum 自然。" }] } },
      { number: 32, position: "this idea of a standard accent is __(32)__", answer: "E", answerWord: "influential", partOfSpeech: "adjective", analysis: { why_correct: "\"is influential\" 意为\"有影响力的\"。虽然语言学家说标准口音是虚构的，但这个概念依然有很大的影响力。", grammar_clue: "is + 形容词，做表语。", context_clue: "Even so 表示转折：虽然标准不存在，但这个观念 is __(32)__，后面紧跟 and many workplace and educational environments perpetuate the idea。", collocation: "an influential idea / remain influential / is influential 是描述观念影响力的自然表达。", common_mistakes: [{ wrong: "O (unanimous)", reason: "is unanimous 描述的不是\"观念\"而是\"共识\"。" }] } },
      { number: 33, position: "accents that __(33)__ from the current standard", answer: "C", answerWord: "deviate", partOfSpeech: "verb", analysis: { why_correct: "\"deviate from the standard\" 意为\"偏离标准\"。那些偏离当前标准的口音被认为不太得体。", grammar_clue: "that 引导定语从句，空格是从句的谓语动词，后面跟 from。", context_clue: "整段在讨论非标准口音在职场中的接受度问题。", collocation: "deviate from the norm / deviate from the standard / deviate from expectations 是固定搭配。", common_mistakes: [{ wrong: "B (correlate)", reason: "correlate from 不是英语搭配。correlate 搭配的是 with。" }] } },
      { number: 34, position: "more accepted in __(34)__ such as government, law", answer: "D", answerWord: "domains", partOfSpeech: "noun", analysis: { why_correct: "\"in domains such as government, law...\" 意为\"在政府、法律等领域\"。", grammar_clue: "in + 复数名词 + such as 后面列举具体例子。", context_clue: "后面用 such as 举例政府、法律、服务行业，这些都是不同的职业领域。", collocation: "in domains such as / across various domains 是学术写作中的标准表达。", common_mistakes: [{ wrong: "I (properties)", reason: "properties 意为\"属性\"或\"房产\"，in properties such as government 语义不通。" }] } },
      { number: 35, position: "may __(35)__ with differences in class and culture", answer: "B", answerWord: "correlate", partOfSpeech: "verb", analysis: { why_correct: "\"correlate with differences\" 意为\"与差异相关联\"。非标准口音的可接受度可能和阶层、文化差异相关。", grammar_clue: "may + 动词原形 + with。需要一个能和 with 搭配的动词。", context_clue: "后面解释了具体的关联方式：新兴或高声望行业更期待标准口音。", collocation: "correlate with / be correlated with 是学术研究中描述相关性的经典表达。", common_mistakes: [{ wrong: "C (deviate)", reason: "deviate with 不是英语搭配（deviate 搭配 from）。" }] } },
    ],
    options: [
      { letter: "A", word: "affix", pos: "n. 词缀 / v. 粘贴", used: false },
      { letter: "B", word: "correlate", pos: "v. 相关联", used: true },
      { letter: "C", word: "deviate", pos: "v. 偏离", used: true },
      { letter: "D", word: "domains", pos: "n. 领域", used: true },
      { letter: "E", word: "influential", pos: "adj. 有影响力的", used: true },
      { letter: "F", word: "inherently", pos: "adv. 本质上；固有地", used: true },
      { letter: "G", word: "laymen", pos: "n. 外行人", used: true },
      { letter: "H", word: "multiple", pos: "adj. 多个的", used: true },
      { letter: "I", word: "properties", pos: "n. 属性；房产", used: false },
      { letter: "J", word: "reality", pos: "n. 现实", used: true },
      { letter: "K", word: "reciprocally", pos: "adv. 互相地", used: false },
      { letter: "L", word: "specimen", pos: "n. 样本；标本", used: false },
      { letter: "M", word: "spectrum", pos: "n. 范围；光谱", used: true },
      { letter: "N", word: "synonym", pos: "n. 同义词", used: true },
      { letter: "O", word: "unanimous", pos: "adj. 一致同意的", used: false },
    ],
    distractors: [
      { letter: "A", word: "affix", explanation: "意为\"词缀\"。文中不涉及词缀的概念。" },
      { letter: "I", word: "properties", explanation: "意为\"属性\"或\"房产\"。文中没有讨论物理属性或财产。" },
      { letter: "K", word: "reciprocally", explanation: "意为\"互相地\"。文中没有涉及双向关系的描述。" },
      { letter: "L", word: "specimen", explanation: "意为\"样本、标本\"。和\"现实\"不构成自然对比。" },
      { letter: "O", word: "unanimous", explanation: "意为\"一致同意的\"。整篇文章都在强调标准并不一致，用 unanimous 会自相矛盾。" },
    ],
    vocabulary_collection: [
      { expression: "a synonym for", meaning: "……的同义词", example: "Accent is not a synonym for dialect" },
      { expression: "umbrella term", meaning: "总称；笼统术语", example: "Dialect is an umbrella term" },
      { expression: "laymen", meaning: "外行人", example: "Many laymen presume..." },
      { expression: "inherently", meaning: "本质上；固有地", example: "inherently the best form of speech" },
      { expression: "an ideal rather than a reality", meaning: "理想而非现实", example: "better understood as an ideal rather than a reality" },
      { expression: "multiple", meaning: "多个的", example: "multiple supposed standards" },
      { expression: "across the spectrum", meaning: "在整个范围内", example: "broadcast outlets across the spectrum" },
      { expression: "deviate from", meaning: "偏离", example: "accents that deviate from the standard" },
      { expression: "perpetuate the idea", meaning: "延续/固化这个观念", example: "educational environments perpetuate the idea" },
      { expression: "correlate with", meaning: "与……相关", example: "may correlate with differences in class and culture" },
    ],
  },
  {
    id: "250601",
    title: "2025年6月 第一套",
    topic: "大学校园除草剂与环保运动",
    article: "In her second year, Charlene Duong learned of the use of poisonous, synthetic pesticides on her college campus. Shocked but not surprised, she knew she had to do something. Along with a couple of classmates, Charlene did a quick web search and discovered a small but growing movement led by the organization, Herbicide-Free Campus (HFC), to rid college campuses of artificial herbicides. They were __(26)__.\nLike many, Charlene experiences climate anxiety -- a __(27)__ fear of a climate catastrophe -- and was, at the time, looking for an __(28)__. When she discovered the HFC movement, she said she felt she \"had found a specific area to focus on that still fit into the larger picture of fighting for a healthier, safer, cleaner __(29)__ for all.\"\nToxic herbicide use in university land care is not unique. Most institutions of higher education rely on synthetic pesticides and fertilizers to achieve __(30)__ goals. Having a \"beautiful\" campus means green and perfectly maintained lawns along with flower beds and paved sidewalks. But these __(31)__ managed campuses can come at a cost: increased cancer risk, __(32)__ waterways, poisoned wildlife and lifeless soil.\nPesticide use on college campuses also contributes to our global climate crisis. The use of chemicals to get rid of insects or unwanted plant life can increase indirect __(33)__, as they can include petroleum-based ingredients. Pesticide use also decreases the life in soil, __(34)__ the ability of soils to absorb carbon or retain water and thus reducing campuses' ability to recover quickly from climate-related extreme weather events like droughts and floods.\nInstead of using toxic chemicals, students working with HFC help out with __(35)__ the campus grounds. \"This work reminds me to be in the present moment as I play my role in reducing herbicide use and keeping my campus safe and healthy,\" says Charlene.",
    blanks: [
      { number: 26, position: "They were __(26)__.", answer: "J", answerWord: "intrigued", partOfSpeech: "adjective (past participle)", analysis: { why_correct: "\"They were intrigued\" 意为\"他们很感兴趣\"。Charlene 和同学发现了 HFC 运动后，感到了兴趣和好奇。", grammar_clue: "were + 形容词/过去分词，做表语。", context_clue: "前文说他们做了搜索、发现了这个运动。整段语气是积极的发现过程。", collocation: "be intrigued by / were intrigued 是描述好奇与兴趣的常见表达。", common_mistakes: [{ wrong: "K (juvenile)", reason: "They were juvenile 意为\"他们是幼稚的\"，与语境不符。" }] } },
      { number: 27, position: "a __(27)__ fear of a climate catastrophe", answer: "B", answerWord: "chronic", partOfSpeech: "adjective", analysis: { why_correct: "\"chronic fear\" 意为\"长期的、持续的恐惧\"。气候焦虑不是一时的恐慌，而是一种持续性的担忧。", grammar_clue: "a + 形容词 + fear，需要形容词修饰 fear。", context_clue: "climate anxiety 被定义为对气候灾难的持续恐惧。chronic 强调这种恐惧是长期性的。", collocation: "chronic fear / chronic anxiety / chronic pain / chronic stress 都是描述长期状态的搭配。", common_mistakes: [{ wrong: "K (juvenile)", reason: "juvenile fear 意为\"幼稚的恐惧\"，贬义且不符合文章对气候焦虑的严肃描述。" }] } },
      { number: 28, position: "looking for an __(28)__", answer: "L", answerWord: "outlet", partOfSpeech: "noun", analysis: { why_correct: "\"looking for an outlet\" 意为\"寻找一个出口/渠道\"。Charlene 有气候焦虑，需要一个能让她把这种焦虑转化为行动的途径。", grammar_clue: "an + 元音开头的单数名词。looking for + 名词。", context_clue: "后面说她发现 HFC 后感觉\"找到了一个具体的领域\"，说明她之前一直在寻找一个行动出口。", collocation: "an outlet for anxiety / an outlet for energy / a creative outlet 是常见搭配。", common_mistakes: [{ wrong: "I (infringement)", reason: "looking for an infringement 语义完全不对。infringement 是负面法律术语。" }] } },
      { number: 29, position: "a healthier, safer, cleaner __(29)__ for all", answer: "F", answerWord: "environment", partOfSpeech: "noun", analysis: { why_correct: "\"a cleaner environment for all\" 意为\"一个对所有人更清洁的环境\"。这是环保运动的核心愿景。", grammar_clue: "a + 形容词 + 单数名词 + for all。三个形容词修饰名词。", context_clue: "整段围绕环保运动，fighting for a healthier, safer, cleaner __(29)__ for all 是对环保目标的总结。", collocation: "a clean/cleaner environment / protect the environment 是最基础的环保搭配。", common_mistakes: [{ wrong: "N (vibrations)", reason: "a cleaner vibrations 语法错误（复数），且语义不通。" }] } },
      { number: 30, position: "to achieve __(30)__ goals", answer: "A", answerWord: "aesthetic", partOfSpeech: "adjective", analysis: { why_correct: "\"aesthetic goals\" 意为\"审美目标\"。大学使用化学除草剂是为了让校园\"看起来漂亮\"。", grammar_clue: "achieve + 形容词 + goals。形容词修饰 goals。", context_clue: "后面紧跟解释：Having a 'beautiful' campus means green and perfectly maintained lawns...。'beautiful' 正对应 aesthetic。", collocation: "aesthetic goals / aesthetic standards / aesthetic appeal 是讨论外观和美感时的标准搭配。", common_mistakes: [{ wrong: "D (conventionally)", reason: "conventionally 是副词，不能直接修饰名词 goals。" }] } },
      { number: 31, position: "these __(31)__ managed campuses", answer: "D", answerWord: "conventionally", partOfSpeech: "adverb", analysis: { why_correct: "\"conventionally managed\" 意为\"以传统方式管理的\"。这些用传统化学方法维护的校园虽然看起来漂亮，但代价很大。", grammar_clue: "副词修饰过去分词 managed。these __(31)__ managed campuses = 副词 + 过去分词 + 名词。", context_clue: "文章正在对比传统管理方式和环保方式。conventionally 暗示这是\"常规做法\"但并非最佳做法。", collocation: "conventionally managed / conventionally grown / conventional methods 是农业和环保领域的常见表达。", common_mistakes: [{ wrong: "A (aesthetic)", reason: "aesthetic managed campuses 语法可行但语义冗余，这里重点在\"管理方式\"而非\"审美\"。" }] } },
      { number: 32, position: "__(32)__ waterways", answer: "C", answerWord: "contaminated", partOfSpeech: "adjective (past participle)", analysis: { why_correct: "\"contaminated waterways\" 意为\"被污染的水道\"。化学除草剂的代价包括癌症风险增加、水源污染、野生动物中毒、土壤死亡。", grammar_clue: "形容词/过去分词修饰 waterways。和前后的 increased, poisoned, lifeless 并列。", context_clue: "这是一个列举句，列出四个代价。contaminated waterways 和 poisoned wildlife、lifeless soil 形成并列。", collocation: "contaminated water / contaminated waterways / contaminated soil 是环境科学中的核心搭配。", common_mistakes: [{ wrong: "M (rotating)", reason: "rotating waterways 意为\"旋转的水道\"，语义荒谬。" }] } },
      { number: 33, position: "increase indirect __(33)__", answer: "E", answerWord: "emissions", partOfSpeech: "noun", analysis: { why_correct: "\"indirect emissions\" 意为\"间接排放\"。使用含石油基成分的农药会增加间接碳排放。", grammar_clue: "increase + 形容词 + 复数名词。indirect 是形容词，后面需要名词。", context_clue: "后面解释 as they can include petroleum-based ingredients，石油基成分正是产生碳排放的原因。", collocation: "indirect emissions / carbon emissions / greenhouse gas emissions 是气候变化讨论中的核心术语。", common_mistakes: [{ wrong: "N (vibrations)", reason: "indirect vibrations 意为\"间接振动\"，和农药使用毫无关系。" }] } },
      { number: 34, position: "__(34)__ the ability of soils to absorb carbon", answer: "G", answerWord: "hampering", partOfSpeech: "verb (present participle)", analysis: { why_correct: "\"hampering the ability\" 意为\"阻碍了……的能力\"。农药减少了土壤中的生命，从而阻碍了土壤吸收碳和保水的能力。", grammar_clue: "现在分词做伴随状语或结果状语。", context_clue: "因果链条：农药→土壤生命减少→吸碳/保水能力受阻→极端天气恢复力下降。", collocation: "hamper the ability / hamper progress / hamper efforts 是描述阻碍的常见搭配。", common_mistakes: [{ wrong: "H (incidentally)", reason: "incidentally 是副词，词性不对。" }] } },
      { number: 35, position: "help out with __(35)__ the campus grounds", answer: "O", answerWord: "weeding", partOfSpeech: "verb (gerund)", analysis: { why_correct: "\"weeding the campus grounds\" 意为\"给校园除草\"。学生不用化学药剂，而是手动除草来维护校园环境。", grammar_clue: "help out with + 动名词（-ing）。with 后面需要名词或动名词。", context_clue: "Instead of using toxic chemicals 开头，说明这是一种替代方案。手动除草是最直接方式。", collocation: "weeding the garden / weeding the grounds / help with weeding 是园艺中的自然表达。", common_mistakes: [{ wrong: "M (rotating)", reason: "rotating the campus grounds 语义不合——讨论的是除草。" }] } },
    ],
    options: [
      { letter: "A", word: "aesthetic", pos: "adj. 审美的；美学的", used: true },
      { letter: "B", word: "chronic", pos: "adj. 慢性的；长期的", used: true },
      { letter: "C", word: "contaminated", pos: "adj. 被污染的", used: true },
      { letter: "D", word: "conventionally", pos: "adv. 传统地；惯常地", used: true },
      { letter: "E", word: "emissions", pos: "n. 排放物", used: true },
      { letter: "F", word: "environment", pos: "n. 环境", used: true },
      { letter: "G", word: "hampering", pos: "v. 阻碍；妨碍", used: true },
      { letter: "H", word: "incidentally", pos: "adv. 顺便说一句", used: false },
      { letter: "I", word: "infringement", pos: "n. 侵犯；违反", used: false },
      { letter: "J", word: "intrigued", pos: "adj. 感兴趣的", used: true },
      { letter: "K", word: "juvenile", pos: "adj. 青少年的；幼稚的", used: false },
      { letter: "L", word: "outlet", pos: "n. 出口；渠道", used: true },
      { letter: "M", word: "rotating", pos: "v. 旋转；轮换", used: false },
      { letter: "N", word: "vibrations", pos: "n. 振动；共鸣", used: false },
      { letter: "O", word: "weeding", pos: "v. 除草", used: true },
    ],
    distractors: [
      { letter: "H", word: "incidentally", explanation: "意为\"顺便说一句\"。文中没有需要插入说明的语境。" },
      { letter: "I", word: "infringement", explanation: "意为\"侵犯\"。looking for an infringement 完全不合逻辑。" },
      { letter: "K", word: "juvenile", explanation: "意为\"青少年的\"或\"幼稚的\"。与积极语境不符。" },
      { letter: "M", word: "rotating", explanation: "意为\"旋转的\"。文中没有涉及旋转的概念。" },
      { letter: "N", word: "vibrations", explanation: "意为\"振动\"。完全与环保主题无关。" },
    ],
    vocabulary_collection: [
      { expression: "synthetic pesticides", meaning: "合成农药", example: "the use of poisonous, synthetic pesticides" },
      { expression: "herbicide-free", meaning: "无除草剂的", example: "Herbicide-Free Campus" },
      { expression: "climate anxiety", meaning: "气候焦虑", example: "Charlene experiences climate anxiety" },
      { expression: "chronic fear", meaning: "长期的恐惧", example: "a chronic fear of a climate catastrophe" },
      { expression: "looking for an outlet", meaning: "寻找一个出口", example: "was looking for an outlet" },
      { expression: "aesthetic goals", meaning: "审美目标", example: "to achieve aesthetic goals" },
      { expression: "conventionally managed", meaning: "以传统方式管理的", example: "conventionally managed campuses" },
      { expression: "contaminated waterways", meaning: "被污染的水道", example: "contaminated waterways" },
      { expression: "indirect emissions", meaning: "间接排放", example: "increase indirect emissions" },
      { expression: "hampering the ability", meaning: "阻碍能力", example: "hampering the ability of soils to absorb carbon" },
    ],
  },
  {
    id: "250602",
    title: "2025年6月 第二套",
    topic: "缓步动物（水熊虫）的极端生存能力",
    article: "No beast on Earth is tougher than the tiny tardigrade. It can __(26)__ being frozen at -272 Celsius, being exposed to the vacuum of outer space and even being __(27)__ with 500 times the dose of X-rays that would kill a human. In other words, the creature can endure conditions that don't even exist on Earth. And researchers are looking to the microscopic animals to learn how to prepare humans and crops to handle the __(28)__ of space travel.\nThe tardigrade's indestructibility stems from its __(29)__ to its environment -- which may seem surprising, since it lives in __(30)__ comfortable places, like the cool, wet patches of moss that dot a garden wall.\nBut it turns out that a tardigrade's damp, mossy home can dry out many times each year. Drying is pretty __(31)__ for most living things. It does damage to cells in some of the same ways that freezing, vacuum and radiation do. Tardigrades, however, have __(32)__ special strategies for dealing with these kinds of damage.\nAs a tardigrade dries out, its cells produce several strange proteins that are unlike anything found in other animals. In water, the proteins are shapeless. But as water disappears, the proteins self-assemble into long fibers that fill the cell's __(33)__. The fibers support the cell's membranes and proteins, preventing them from breaking or __(34)__.\nEmulating tardigrades could one day help humans colonize outer space. Food crops could be engineered to produce tardigrade proteins, allowing these organisms to grow more efficiently on spacecraft where levels of radiation are elevated compared with on Earth.\nSo if humans ever succeed in reaching the stars, they may accomplish this __(35)__, in part, by standing on the shoulders of the tiny eight-legged endurance specialists in your backyard.",
    blanks: [
      { number: 26, position: "It can __(26)__ being frozen at -272 Celsius", answer: "K", answerWord: "survive", partOfSpeech: "verb", analysis: { why_correct: "\"can survive being frozen\" 意为\"能在被冻结的情况下存活\"。水熊虫能抵御极端低温。", grammar_clue: "can + 动词原形 + 动名词（being frozen）。需要一个后面能接 -ing 形式的动词。", context_clue: "整段在列举水熊虫能承受的极端条件：冰冻、真空、辐射。survive 完美对应\"在极端条件下存活\"。", collocation: "survive being frozen / survive extreme conditions 是生物学中的常见搭配。", common_mistakes: [{ wrong: "L (tempt)", reason: "tempt being frozen 语义荒谬。" }] } },
      { number: 27, position: "being __(27)__ with 500 times the dose of X-rays", answer: "B", answerWord: "blasted", partOfSpeech: "verb (past participle)", analysis: { why_correct: "\"being blasted with X-rays\" 意为\"被X射线轰击\"。blast 在此表示\"用强烈的力量照射/轰击\"。", grammar_clue: "being + 过去分词，被动语态。后面跟 with 表示\"用……\"。", context_clue: "前面列举了冰冻和真空，这是第三个极端条件：高剂量辐射轰击。", collocation: "blasted with radiation / blasted with X-rays 是描述高强度辐射的生动表达。", common_mistakes: [{ wrong: "C (catastrophic)", reason: "catastrophic 是形容词，being catastrophic with 语法不通。" }] } },
      { number: 28, position: "handle the __(28)__ of space travel", answer: "I", answerWord: "rigors", partOfSpeech: "noun", analysis: { why_correct: "\"the rigors of space travel\" 意为\"太空旅行的严酷考验\"。研究者想从水熊虫身上学习如何应对太空的极端环境。", grammar_clue: "the + 复数名词 + of。handle 的宾语。", context_clue: "前文列举了冰冻、真空、辐射等极端条件，这些正是太空旅行的 rigors（严酷考验）。", collocation: "the rigors of / endure the rigors of / face the rigors of 是描述艰苦条件的经典搭配。", common_mistakes: [{ wrong: "H (recurrence)", reason: "the recurrence of space travel 不符合语境——讨论的是太空的严酷环境。" }] } },
      { number: 29, position: "stems from its __(29)__ to its environment", answer: "A", answerWord: "adaptations", partOfSpeech: "noun", analysis: { why_correct: "\"adaptations to its environment\" 意为\"对环境的适应\"。水熊虫的坚不可摧源于它对环境的适应能力。", grammar_clue: "its + 复数名词 + to。stems from 的宾语。", context_clue: "后文详细解释了水熊虫如何适应干燥环境——产生特殊蛋白质等。", collocation: "adaptations to the environment / biological adaptations 是生物学核心术语。", common_mistakes: [{ wrong: "D (evolved)", reason: "its evolved to 语法错误——evolved 是动词，不能放在 its 后面做名词用。" }] } },
      { number: 30, position: "it lives in __(30)__ comfortable places", answer: "J", answerWord: "seemingly", partOfSpeech: "adverb", analysis: { why_correct: "\"seemingly comfortable places\" 意为\"看似舒适的地方\"。水熊虫生活在花园墙上的苔藓中——看起来很舒适，但实际上这些地方经常干燥。", grammar_clue: "副词修饰形容词 comfortable。", context_clue: "后面用 But it turns out 转折，说明这些\"看似舒适\"的地方其实会频繁干燥。", collocation: "seemingly comfortable / seemingly harmless / seemingly simple 是表示\"表面上看起来……\"的常见搭配。", common_mistakes: [{ wrong: "N (unanimously)", reason: "unanimously comfortable 语义荒谬。" }] } },
      { number: 31, position: "Drying is pretty __(31)__ for most living things", answer: "C", answerWord: "catastrophic", partOfSpeech: "adjective", analysis: { why_correct: "\"pretty catastrophic\" 意为\"相当灾难性的\"。干燥对大多数生物来说是毁灭性的。", grammar_clue: "is + pretty + 形容词。", context_clue: "后面解释 It does damage to cells，说明干燥的破坏力很强。", collocation: "catastrophic for / catastrophic damage / catastrophic consequences 是常用搭配。", common_mistakes: [{ wrong: "M (thrill)", reason: "Drying is pretty thrill 语法错误（thrill 不是形容词）。" }] } },
      { number: 32, position: "have __(32)__ special strategies", answer: "D", answerWord: "evolved", partOfSpeech: "verb (past participle)", analysis: { why_correct: "\"have evolved special strategies\" 意为\"进化出了特殊策略\"。水熊虫通过进化发展出了应对干燥的独特机制。", grammar_clue: "have + 过去分词，现在完成时态。", context_clue: "文章在讲生物进化——水熊虫不是\"学会\"了这些策略，而是经过漫长进化\"发展出\"了它们。", collocation: "evolved strategies / evolved mechanisms 是进化生物学的常见表达。", common_mistakes: [{ wrong: "G (probing)", reason: "have probing 语法错误。" }] } },
      { number: 33, position: "fill the cell's __(33)__", answer: "F", answerWord: "interior", partOfSpeech: "noun", analysis: { why_correct: "\"fill the cell's interior\" 意为\"填满细胞内部\"。蛋白质纤维充满了细胞内部空间，起到支撑作用。", grammar_clue: "fill + the + 所有格 + 单数名词。需要一个表示空间的名词。", context_clue: "后面说 The fibers support the cell's membranes and proteins，支撑作用需要先\"填满内部\"才能实现。", collocation: "cell interior / the interior of the cell 是细胞生物学的标准表达。", common_mistakes: [{ wrong: "H (recurrence)", reason: "fill the cell's recurrence 完全不合逻辑。" }] } },
      { number: 34, position: "preventing them from breaking or __(34)__", answer: "O", answerWord: "unfolding", partOfSpeech: "verb (gerund)", analysis: { why_correct: "\"breaking or unfolding\" 意为\"断裂或解折叠\"。蛋白质的功能取决于其折叠结构，unfolding 意味着蛋白质变性失效。", grammar_clue: "from + -ing + or + -ing，两个动名词并列。", context_clue: "蛋白质在脱水时可能断裂或失去折叠结构。和 breaking 并列，描述了两种不同的损伤方式。", collocation: "protein unfolding / prevent unfolding / protein misfolding 是分子生物学术语。", common_mistakes: [{ wrong: "G (probing)", reason: "preventing from probing 和细胞保护机制完全无关。" }] } },
      { number: 35, position: "they may accomplish this __(35)__", answer: "E", answerWord: "feat", partOfSpeech: "noun", analysis: { why_correct: "\"accomplish this feat\" 意为\"完成这一壮举\"。到达星际是人类的伟大壮举。", grammar_clue: "accomplish + this + 单数名词。需要一个表示\"成就\"的名词。", context_clue: "reaching the stars 是一个宏大的目标，feat（壮举）是对这个成就的恰当描述。", collocation: "accomplish a feat / achieve a feat / an incredible feat 是描述重大成就的经典搭配。", common_mistakes: [{ wrong: "M (thrill)", reason: "accomplish this thrill 不通——你不能\"完成\"一种感觉。" }] } },
    ],
    options: [
      { letter: "A", word: "adaptations", pos: "n. 适应；改编", used: true },
      { letter: "B", word: "blasted", pos: "v. 轰击；爆炸", used: true },
      { letter: "C", word: "catastrophic", pos: "adj. 灾难性的", used: true },
      { letter: "D", word: "evolved", pos: "v. 进化；发展", used: true },
      { letter: "E", word: "feat", pos: "n. 壮举；功绩", used: true },
      { letter: "F", word: "interior", pos: "n. 内部", used: true },
      { letter: "G", word: "probing", pos: "v. 探测；调查", used: false },
      { letter: "H", word: "recurrence", pos: "n. 复发", used: false },
      { letter: "I", word: "rigors", pos: "n. 严酷；严苛", used: true },
      { letter: "J", word: "seemingly", pos: "adv. 看似；表面上", used: true },
      { letter: "K", word: "survive", pos: "v. 存活；幸存", used: true },
      { letter: "L", word: "tempt", pos: "v. 诱惑", used: false },
      { letter: "M", word: "thrill", pos: "n./v. 刺激", used: false },
      { letter: "N", word: "unanimously", pos: "adv. 一致地", used: false },
      { letter: "O", word: "unfolding", pos: "v. 展开；打开", used: true },
    ],
    distractors: [
      { letter: "G", word: "probing", explanation: "意为\"探测\"。文中没有涉及调查的语境。" },
      { letter: "H", word: "recurrence", explanation: "意为\"复发\"。和太空旅行严酷环境无关。" },
      { letter: "L", word: "tempt", explanation: "意为\"引诱\"。文中没有任何\"引诱\"的语境。" },
      { letter: "M", word: "thrill", explanation: "意为\"刺激\"。accomplish this thrill 不通。" },
      { letter: "N", word: "unanimously", explanation: "意为\"一致地\"。文中没有需要表达\"一致同意\"的语境。" },
    ],
    vocabulary_collection: [
      { expression: "tardigrade", meaning: "缓步动物（水熊虫）", example: "No beast on Earth is tougher than the tiny tardigrade" },
      { expression: "survive being frozen", meaning: "在冰冻状态下存活", example: "can survive being frozen at -272 Celsius" },
      { expression: "blasted with", meaning: "被……轰击", example: "being blasted with 500 times the dose of X-rays" },
      { expression: "the rigors of", meaning: "……的严酷考验", example: "handle the rigors of space travel" },
      { expression: "adaptations to", meaning: "对……的适应", example: "adaptations to its environment" },
      { expression: "seemingly comfortable", meaning: "看似舒适的", example: "seemingly comfortable places" },
      { expression: "catastrophic for", meaning: "对……是灾难性的", example: "catastrophic for most living things" },
      { expression: "evolved strategies", meaning: "进化出的策略", example: "evolved special strategies for dealing with damage" },
      { expression: "cell's interior", meaning: "细胞内部", example: "fill the cell's interior" },
      { expression: "accomplish this feat", meaning: "完成这一壮举", example: "they may accomplish this feat" },
    ],
  },
  {
    id: "250603",
    title: "2025年6月 第三套",
    topic: "女性在美国国会中的代表性不足",
    article: "The slow progress of women in elective office is frustrating for some political observers and experts -- including myself. Achieving gender equality in Congress is an important goal. This is because the number of women involved in legislative decisions has significant __(26)__ for all the policies that governments __(27)__. Female legislators are more likely than men to introduce, speak about and work to pass policies that disproportionately affect women and girls, such as paid family leave, pay __(28)__ and gender-based violence.\nHaving more women in Congress also fosters a greater sense of connection between female voters and government. In addition, it __(29)__ women's sense that government cares about their concerns and inspires young women to become more politically engaged.\nWhile women are underrepresented in governments around the globe, it is a particularly __(30)__ problem in the United States. Currently, the U.S. ranks 73rd in the world when it comes to female representation in government.\nBut the reason women are so __(31)__ underrepresented in U.S. government is not because they face resistance from voters or struggle to raise money. On the contrary, decades of research shows that female candidates raise as much money and win as often as male politicians with similar __(32)__.\nRather, the slow progress of women in politics is a tale of two political parties.\nIn the next Congress, there will be 107 female Democratic lawmakers and 42 female Republican lawmakers in the Senate and House combined.\nIn order for women to gain half of the seats in Congress, more women need to run, __(33)__ on Republican tickets. This will require the Republican Party as a whole to __(34)__ recruiting women -- and not just for one election cycle, but in a __(35)__ way.",
    blanks: [
      { number: 26, position: "has significant __(26)__ for all the policies", answer: "B", answerWord: "consequences", partOfSpeech: "noun", analysis: { why_correct: "\"significant consequences for\" 意为\"对……有重大影响/后果\"。", grammar_clue: "significant + 复数名词 + for。has 的宾语。", context_clue: "后面详细解释了这种影响：女性立法者更可能推动涉及女性权益的政策。", collocation: "significant consequences for / have consequences for / far-reaching consequences 是政策讨论中的核心搭配。", common_mistakes: [{ wrong: "J (impetus)", reason: "significant impetus for 语法可行，但 consequences for 比 impetus for 更准确。" }] } },
      { number: 27, position: "policies that governments __(27)__", answer: "E", answerWord: "enact", partOfSpeech: "verb", analysis: { why_correct: "\"policies that governments enact\" 意为\"政府制定的政策\"。enact 在政治语境中意为\"制定/颁布\"。", grammar_clue: "that 引导定语从句，governments 是主语，需要谓语动词。", context_clue: "整段在讨论立法和政策制定，enact 是最准确的动词。", collocation: "enact policies / enact legislation / enact laws 是政治学和法学的核心表达。", common_mistakes: [{ wrong: "M (suffices)", reason: "policies that governments suffices 语法错误，且语义不对。" }] } },
      { number: 28, position: "paid family leave, pay __(28)__ and gender-based violence", answer: "F", answerWord: "equity", partOfSpeech: "noun", analysis: { why_correct: "\"pay equity\" 意为\"薪酬公平\"。和带薪家庭假、性别暴力并列，都是特别影响女性的政策领域。", grammar_clue: "pay + 名词，构成复合名词。", context_clue: "这三个并列项都是女性权益的核心议题：产假→薪酬公平→性别暴力。", collocation: "pay equity / gender equity 是性别平等讨论中的核心术语。", common_mistakes: [{ wrong: "K (lavish)", reason: "pay lavish 不构成有意义的复合名词。" }] } },
      { number: 29, position: "it __(29)__ women's sense that government cares", answer: "A", answerWord: "bolsters", partOfSpeech: "verb", analysis: { why_correct: "\"bolsters women's sense\" 意为\"增强了女性的感受/信念\"。", grammar_clue: "it + 动词（第三人称单数）+ 宾语。需要及物动词。", context_clue: "前面说 fosters a greater sense of connection，这里继续说 bolsters women's sense，两个正面效果并列。", collocation: "bolster confidence / bolster a sense of 是描述\"增强\"的正式表达。", common_mistakes: [{ wrong: "M (suffices)", reason: "it suffices women's sense 语义不对。" }] } },
      { number: 30, position: "a particularly __(30)__ problem in the United States", answer: "I", answerWord: "formidable", partOfSpeech: "adjective", analysis: { why_correct: "\"a formidable problem\" 意为\"一个严峻的/棘手的问题\"。", grammar_clue: "a + particularly + 形容词 + problem。", context_clue: "后面用数据支撑：美国在女性政治代表方面全球排名第73位。", collocation: "a formidable problem / a formidable challenge 是描述严峻问题的常见搭配。", common_mistakes: [{ wrong: "O (tenured)", reason: "a tenured problem 不是自然搭配。" }] } },
      { number: 31, position: "women are so __(31)__ underrepresented", answer: "D", answerWord: "dramatically", partOfSpeech: "adverb", analysis: { why_correct: "\"so dramatically underrepresented\" 意为\"如此严重地代表性不足\"。", grammar_clue: "so + 副词 + 形容词/过去分词。", context_clue: "后面紧跟 is not because... On the contrary...，作者在强调程度之深。", collocation: "dramatically underrepresented / dramatically different 是表达显著程度的常见搭配。", common_mistakes: [{ wrong: "H (evasively)", reason: "evasively underrepresented 语义不通。" }] } },
      { number: 32, position: "male politicians with similar __(32)__", answer: "C", answerWord: "credentials", partOfSpeech: "noun", analysis: { why_correct: "\"with similar credentials\" 意为\"拥有类似资历的\"。", grammar_clue: "with + similar + 复数名词。", context_clue: "在资历相似的情况下，女性候选人筹款能力和胜选率与男性一样。", collocation: "similar credentials / academic credentials / professional credentials 是描述资历的标准搭配。", common_mistakes: [{ wrong: "B (consequences)", reason: "with similar consequences 比较的是后果而非资质。" }] } },
      { number: 33, position: "more women need to run, __(33)__ on Republican tickets", answer: "G", answerWord: "especially", partOfSpeech: "adverb", analysis: { why_correct: "\"especially on Republican tickets\" 意为\"尤其是以共和党身份参选\"。", grammar_clue: "逗号后面跟副词，起补充强调作用。", context_clue: "前面数据：民主党女性107人 vs 共和党女性42人。差距明显在共和党一侧。", collocation: "especially in / especially on / especially when 是常见用法。", common_mistakes: [{ wrong: "H (evasively)", reason: "evasively on Republican tickets 语义荒谬。" }] } },
      { number: 34, position: "the Republican Party as a whole to __(34)__ recruiting women", answer: "L", answerWord: "prioritize", partOfSpeech: "verb", analysis: { why_correct: "\"prioritize recruiting women\" 意为\"优先招募女性\"。", grammar_clue: "to + 动词原形 + 动名词。", context_clue: "整段都在论证共和党是女性政治参与不足的关键瓶颈。", collocation: "prioritize recruiting / prioritize diversity 是管理和政策语境中的常见搭配。", common_mistakes: [{ wrong: "A (bolsters)", reason: "to bolsters 语法错误（to 后面应跟原形）。" }] } },
      { number: 35, position: "in a __(35)__ way", answer: "N", answerWord: "sustained", partOfSpeech: "adjective", analysis: { why_correct: "\"in a sustained way\" 意为\"以持续的方式\"。不只是一个选举周期，而是要长期坚持。", grammar_clue: "in a + 形容词 + way。", context_clue: "前面说 not just for one election cycle，与之对应的是 in a sustained way。", collocation: "in a sustained way / sustained effort / sustained growth 是描述长期性的常见搭配。", common_mistakes: [{ wrong: "K (lavish)", reason: "in a lavish way 不符合\"持续努力\"的论点。" }] } },
    ],
    options: [
      { letter: "A", word: "bolsters", pos: "v. 增强；支持", used: true },
      { letter: "B", word: "consequences", pos: "n. 后果；影响", used: true },
      { letter: "C", word: "credentials", pos: "n. 资历；证书", used: true },
      { letter: "D", word: "dramatically", pos: "adv. 显著地", used: true },
      { letter: "E", word: "enact", pos: "v. 制定；颁布", used: true },
      { letter: "F", word: "equity", pos: "n. 公平；公正", used: true },
      { letter: "G", word: "especially", pos: "adv. 尤其", used: true },
      { letter: "H", word: "evasively", pos: "adv. 回避地", used: false },
      { letter: "I", word: "formidable", pos: "adj. 严峻的", used: true },
      { letter: "J", word: "impetus", pos: "n. 推动力", used: false },
      { letter: "K", word: "lavish", pos: "adj. 奢华的", used: false },
      { letter: "L", word: "prioritize", pos: "v. 优先处理", used: true },
      { letter: "M", word: "suffices", pos: "v. 足够", used: false },
      { letter: "N", word: "sustained", pos: "adj. 持续的", used: true },
      { letter: "O", word: "tenured", pos: "adj. 有终身职位的", used: false },
    ],
    distractors: [
      { letter: "H", word: "evasively", explanation: "意为\"回避地\"。文中没有涉及回避的语境。" },
      { letter: "J", word: "impetus", explanation: "意为\"推动力\"。consequences for 比 impetus for 更准确。" },
      { letter: "K", word: "lavish", explanation: "意为\"奢华的\"。文中没有涉及奢华的描述。" },
      { letter: "M", word: "suffices", explanation: "意为\"足够\"。语法和语义都不合适。" },
      { letter: "O", word: "tenured", explanation: "意为\"有终身职位的\"。和政治话题完全无关。" },
    ],
    vocabulary_collection: [
      { expression: "elective office", meaning: "民选公职", example: "The slow progress of women in elective office" },
      { expression: "significant consequences for", meaning: "对……有重大影响", example: "significant consequences for all the policies" },
      { expression: "enact policies", meaning: "制定/颁布政策", example: "policies that governments enact" },
      { expression: "pay equity", meaning: "薪酬公平", example: "paid family leave, pay equity and gender-based violence" },
      { expression: "bolster", meaning: "增强；支持", example: "it bolsters women's sense" },
      { expression: "a formidable problem", meaning: "一个严峻的问题", example: "a particularly formidable problem" },
      { expression: "dramatically underrepresented", meaning: "严重代表性不足", example: "so dramatically underrepresented" },
      { expression: "similar credentials", meaning: "类似的资历", example: "male politicians with similar credentials" },
      { expression: "prioritize recruiting", meaning: "优先招募", example: "prioritize recruiting women" },
      { expression: "in a sustained way", meaning: "以持续的方式", example: "not just for one election cycle, but in a sustained way" },
    ],
  },
];
